var items = 0;
        let change_event_adder = () => {
            var dropdowns = document.querySelectorAll(".change1");
            dropdowns.forEach((dropdown) => {
                dropdown.addEventListener("change", () => {
                    change1(dropdown);
                });
            });
        };
        function addItem1() {

            items++;
            var html = "<tr>";
            html += "<td>";
            html += "<select class='change1' id='" + items + "' name='type_" + items + "'>";
            html += "<option value='E/D' selected>E/D</option>";
            html += "<option value='Tab'>Tab</option>";
            html += "<option value='Syrup'>Syrup</option>";
            html += "<option value='Cap'>Cap</option>";
            html += "</select>";
            html += "</td>";
            html += "<td>";
            html += "<input type='text' class='live-fetch-2' style='width:20rem;' name='med_name_" + items + "'>";
            html += " <div class='dropdown-container' ></div></td>";
            html += "<td>";
            html += "<select name='morning_" + items + "'>";
            html += "<option value='0'>0</option>";
            html += "<option value='1 थेंब'>1 थेंब</option>";
            html += "<option value='2 थेंब'>2 थेंब</option>";
            html += "<option value='3 थेंब '>3 थेंब </option>";
            html += "<option value='4 थेंब'>4 थेंब</option>";
            html += "<option value='5 थेंब'>5 थेंब </option>";
            html += "<option value='6 थेंब'>6 थेंब</option>";
            html += "<option value='7 थेंब'>7 थेंब </option>";
            html += "<option value='8 थेंब'>8 थेंब</option>";
            html += "<option value='9 थेंब'>9 थेंब </option>";
            html += "<option value='10 थेंब'>10 थेंब</option>";
            html += "</select>";
            html += "</td>";
            html += "<td>";
            html += "<select name='afternoon_" + items + "'>";
            html += "<option value='0'>0</option>";
            html += "<option value='1 थेंब'>1 थेंब</option>";
            html += "<option value='2 थेंब'>2 थेंब</option>";
            html += "<option value='3 थेंब '>3 थेंब </option>";
            html += "<option value='4 थेंब'>4 थेंब</option>";
            html += "<option value='5 थेंब'>5 थेंब </option>";
            html += "<option value='6 थेंब'>6 थेंब</option>";
            html += "<option value='7 थेंब'>7 थेंब </option>";
            html += "<option value='8 थेंब'>8 थेंब</option>";
            html += "<option value='9 थेंब'>9 थेंब </option>";
            html += "<option value='10 थेंब'>10 थेंब</option>";
            html += "</select>";
            html += "</td>";
            html += "<td>";
            html += "<select name='night_" + items + "'>";
            html += "<option value='0'>0</option>";
            html += "<option value='1 थेंब'>1 थेंब</option>";
            html += "<option value='2 थेंब'>2 थेंब</option>";
            html += "<option value='3 थेंब '>3 थेंब </option>";
            html += "<option value='4 थेंब'>4 थेंब</option>";
            html += "<option value='5 थेंब'>5 थेंब </option>";
            html += "<option value='6 थेंब'>6 थेंब</option>";
            html += "<option value='7 थेंब'>7 थेंब </option>";
            html += "<option value='8 थेंब'>8 थेंब</option>";
            html += "<option value='9 थेंब'>9 थेंब </option>";
            html += "<option value='10 थेंब'>10 थेंब</option>";
            html += "</select>";
            html += "</td>";
            html += "<td></td>";
            html += "<td><input type='text' name='days_" + items + "'></td>";
            html += "<td><input type='number' name='quantity_" + items + "'></td>";
            html += "<td><button class='btn btn-primary' type='button' onclick='deleteRow1(this);'>Delete</button></td>";
            html += "</tr>";
            var row = document.getElementById("tbody").insertRow();
            row.innerHTML = html;
            change_event_adder();
            liveFetchElements2();
        }

        function change1(btn) {
            var e = btn.value;
            //console.log(e);
            var id = btn.id;
            //console.log(id);
            var content = btn.parentElement.parentElement;
            //console.log(content);

            var html = "<tr>";
            html += "<td>";
            html += "<select class='change1' id='" + id + "' name='type_" + id + "'>";
            if (e === 'E/D') {
                //console.log('want to change to E/D');

                html += "<option value='E/D' selected>E/D</option>";
                html += "<option value='Tab'>Tab</option>";
                html += "<option value='Syrup'>Syrup</option>";
                html += "<option value='Cap'>Cap</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<input type='text' class='live-fetch-2' style='width:20rem;' name='med_name_" + id + "'>";
                html += "<div class='dropdown-container' ></div></td>";
                html += "<td>";
                html += "<select name='morning_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1 थेंब'>1 थेंब</option>";
                html += "<option value='2 थेंब'>2 थेंब</option>";
                html += "<option value='3 थेंब '>3 थेंब </option>";
                html += "<option value='4 थेंब'>4 थेंब</option>";
                html += "<option value='5 थेंब'>5 थेंब </option>";
                html += "<option value='6 थेंब'>6 थेंब</option>";
                html += "<option value='7 थेंब'>7 थेंब </option>";
                html += "<option value='8 थेंब'>8 थेंब</option>";
                html += "<option value='9 थेंब'>9 थेंब </option>";
                html += "<option value='10 थेंब'>10 थेंब</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<select name='afternoon_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1 थेंब'>1 थेंब</option>";
                html += "<option value='2 थेंब'>2 थेंब</option>";
                html += "<option value='3 थेंब '>3 थेंब </option>";
                html += "<option value='4 थेंब'>4 थेंब</option>";
                html += "<option value='5 थेंब'>5 थेंब </option>";
                html += "<option value='6 थेंब'>6 थेंब</option>";
                html += "<option value='7 थेंब'>7 थेंब </option>";
                html += "<option value='8 थेंब'>8 थेंब</option>";
                html += "<option value='9 थेंब'>9 थेंब </option>";
                html += "<option value='10 थेंब'>10 थेंब</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<select name='night_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1 थेंब'>1 थेंब</option>";
                html += "<option value='2 थेंब'>2 थेंब</option>";
                html += "<option value='3 थेंब '>3 थेंब </option>";
                html += "<option value='4 थेंब'>4 थेंब</option>";
                html += "<option value='5 थेंब'>5 थेंब </option>";
                html += "<option value='6 थेंब'>6 थेंब</option>";
                html += "<option value='7 थेंब'>7 थेंब </option>";
                html += "<option value='8 थेंब'>8 थेंब</option>";
                html += "<option value='9 थेंब'>9 थेंब </option>";
                html += "<option value='10 थेंब'>10 थेंब</option>";
                html += "</select>";
                html += "</td>";
                html += "<td></td>";

            } else if (e === 'Syrup') {
                //console.log('want to change to syrup');
                html += "<option value='E/D'>E/D</option>";
                html += "<option value='Tab'>Tab</option>";
                html += "<option value='Syrup' selected>Syrup</option>";
                html += "<option value='Cap'>Cap</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<input type='text' class='live-fetch-2' style='width:20rem;' name='med_name_" + id + "'>";
                html += "<div class='dropdown-container' ></div></td>";
                html += "<td>";
                html += "<select name='morning_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1 ml'>1 ml</option>";
                html += "<option value='2 ml'>2 ml</option>";
                html += "<option value='3 ml'>3 ml</option>";
                html += "<option value='4 ml'>4 ml</option>";
                html += "<option value='5 ml'>5 ml</option>";
                html += "<option value='6 ml'>6 ml</option>";
                html += "<option value='7 ml'>7 ml</option>";
                html += "<option value='8 ml'>8 ml</option>";
                html += "<option value='9 ml'>9 ml</option>";
                html += "<option value='10 ml'>10 ml</option>";
                html += "<option value='11 ml'>11 ml</option>";
                html += "<option value='12 ml'>12 ml</option>";
                html += "<option value='13 ml'>13 ml</option>";
                html += "<option value='14 ml'>14 ml</option>";
                html += "<option value='15 ml'>15 ml</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<select name='afternoon_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1 ml'>1 ml</option>";
                html += "<option value='2 ml'>2 ml</option>";
                html += "<option value='3 ml'>3 ml</option>";
                html += "<option value='4 ml'>4 ml</option>";
                html += "<option value='5 ml'>5 ml</option>";
                html += "<option value='6 ml'>6 ml</option>";
                html += "<option value='7 ml'>7 ml</option>";
                html += "<option value='8 ml'>8 ml</option>";
                html += "<option value='9 ml'>9 ml</option>";
                html += "<option value='10 ml'>10 ml</option>";
                html += "<option value='11 ml'>11 ml</option>";
                html += "<option value='12 ml'>12 ml</option>";
                html += "<option value='13 ml'>13 ml</option>";
                html += "<option value='14 ml'>14 ml</option>";
                html += "<option value='15 ml'>15 ml</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<select name='night_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1 ml'>1 ml</option>";
                html += "<option value='2 ml'>2 ml</option>";
                html += "<option value='3 ml'>3 ml</option>";
                html += "<option value='4 ml'>4 ml</option>";
                html += "<option value='5 ml'>5 ml</option>";
                html += "<option value='6 ml'>6 ml</option>";
                html += "<option value='7 ml'>7 ml</option>";
                html += "<option value='8 ml'>8 ml</option>";
                html += "<option value='9 ml'>9 ml</option>";
                html += "<option value='10 ml'>10 ml</option>";
                html += "<option value='11 ml'>11 ml</option>";
                html += "<option value='12 ml'>12 ml</option>";
                html += "<option value='13 ml'>13 ml</option>";
                html += "<option value='14 ml'>14 ml</option>";
                html += "<option value='15 ml'>15 ml</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<select name='eat_" + id + "'>";
                html += "<option value='जेवणा नंतर'>जेवणा नंतर</option>";
                html += "<option value='जेवणा आगोदर'>जेवणा आगोदर</option>";
                html += "</select>";
                html += "</td>";

            } else if (e === 'Cap') {
                //console.log('want to change to cap');
                html += "<option value='E/D'>E/D</option>";
                html += "<option value='Tab'>Tab</option>";
                html += "<option value='Syrup'>Syrup</option>";
                html += "<option value='Cap' selected>Cap</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<input type='text' class='live-fetch-2' style='width:20rem;' name='med_name_" + id + "'>";
                html += "<div class='dropdown-container' ></div></td>";
                html += "<td>";
                html += "<select name='morning_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1/2'>1/2</option>";
                html += "<option value='1'>1</option>";
                html += "<option value='2'>2</option>";
                html += "<option value='3'>3</option>";
                html += "<option value='4'>4</option>";
                html += "<option value='5'>5</option>";
                html += "<option value='6'>6</option>";
                html += "<option value='7'>7</option>";
                html += "<option value='8'>8</option>";
                html += "<option value='9'>9</option>";
                html += "<option value='10'>10</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<select name='afternoon_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1/2'>1/2</option>";
                html += "<option value='1'>1</option>";
                html += "<option value='2'>2</option>";
                html += "<option value='3'>3</option>";
                html += "<option value='4'>4</option>";
                html += "<option value='5'>5</option>";
                html += "<option value='6'>6</option>";
                html += "<option value='7'>7</option>";
                html += "<option value='8'>8</option>";
                html += "<option value='9'>9</option>";
                html += "<option value='10'>10</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<select name='night_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1/2'>1/2</option>";
                html += "<option value='1'>1</option>";
                html += "<option value='2'>2</option>";
                html += "<option value='3'>3</option>";
                html += "<option value='4'>4</option>";
                html += "<option value='5'>5</option>";
                html += "<option value='6'>6</option>";
                html += "<option value='7'>7</option>";
                html += "<option value='8'>8</option>";
                html += "<option value='9'>9</option>";
                html += "<option value='10'>10</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<select name='eat_" + id + "'>";
                html += "<option value='जेवणा नंतर'>जेवणा नंतर</option>";
                html += "<option value='जेवणा आगोदर'>जेवणा आगोदर</option>";
                html += "</select>";
                html += "</td>";

            } else if (e === 'Tab') {
                //console.log('want to change to tab');
                html += "<option value='E/D'>E/D</option>";
                html += "<option value='Tab' selected>Tab</option>";
                html += "<option value='Syrup'>Syrup</option>";
                html += "<option value='Cap'>Cap</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<input type='text' class='live-fetch-2' style='width:20rem;' name='med_name_" + id + "'>";
                html += "<div class='dropdown-container' ></div></td>";
                html += "<td>";
                html += "<select name='morning_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1/2'>1/2</option>";
                html += "<option value='1'>1</option>";
                html += "<option value='2'>2</option>";
                html += "<option value='3'>3</option>";
                html += "<option value='4'>4</option>";
                html += "<option value='5'>5</option>";
                html += "<option value='6'>6</option>";
                html += "<option value='7'>7</option>";
                html += "<option value='8'>8</option>";
                html += "<option value='9'>9</option>";
                html += "<option value='10'>10</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<select name='afternoon_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1/2'>1/2</option>";
                html += "<option value='1'>1</option>";
                html += "<option value='2'>2</option>";
                html += "<option value='3'>3</option>";
                html += "<option value='4'>4</option>";
                html += "<option value='5'>5</option>";
                html += "<option value='6'>6</option>";
                html += "<option value='7'>7</option>";
                html += "<option value='8'>8</option>";
                html += "<option value='9'>9</option>";
                html += "<option value='10'>10</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<select name='night_" + id + "'>";
                html += "<option value='0'>0</option>";
                html += "<option value='1/2'>1/2</option>";
                html += "<option value='1'>1</option>";
                html += "<option value='2'>2</option>";
                html += "<option value='3'>3</option>";
                html += "<option value='4'>4</option>";
                html += "<option value='5'>5</option>";
                html += "<option value='6'>6</option>";
                html += "<option value='7'>7</option>";
                html += "<option value='8'>8</option>";
                html += "<option value='9'>9</option>";
                html += "<option value='10'>10</option>";
                html += "</select>";
                html += "</td>";
                html += "<td>";
                html += "<select name='eat_" + id + "'>";
                html += "<option value='जेवणा नंतर'>जेवणा नंतर</option>";
                html += "<option value='जेवणा आगोदर'>जेवणा आगोदर</option>";
                html += "</select>";
                html += "</td>";

            }
            html += "<td><input type='text' name='days_" + id + "'></td>";
            html += "<td><input type='text' name='quantity_" + id + "'></td>";
            html += "<td><button class='btn btn-primary' type='button' onclick='deleteRow1(this);'>Delete</button></td>";
            html += "</tr>";
            //console.log(html);
            //console.log(content);
            content.innerHTML = html;
            change_event_adder();
            
            liveFetchElements2();
        }

        function deleteRow1(button) {
            var delete_name = button.parentElement.parentElement.children[1].children[0];
            delete_name.value = "";
            delete_name.parentElement.parentElement.style.display = "none";
        }
