<?php
$id = $_GET['id'];
require("../admin/connect.php");
$complaints = $_POST["complaints"];
$past_his = $_POST["past_his"];
$fees = $_POST["fees"];
$visit_no = $_POST["visit_no"];
$dist_input_1 = $_POST["dist_input_1"];
$dist_input_2 = $_POST["dist_input_2"];
$dist_input_3 = $_POST["dist_input_3"];
$dist_input_4 = $_POST["dist_input_4"];
$dist_input_5 = $_POST["dist_input_5"];
$dist_input_6 = $_POST["dist_input_6"];
$dist_input_7 = $_POST["dist_input_7"];
$dist_input_8 = $_POST["dist_input_8"];
$near_input_1 = $_POST["near_input_1"];
$near_input_2 = $_POST["near_input_2"];
$near_input_3 = $_POST["near_input_3"];
$near_input_4 = $_POST["near_input_4"];
$near_input_5 = $_POST["near_input_5"];
$near_input_6 = $_POST["near_input_6"];
$near_input_7 = $_POST["near_input_7"];
$near_input_8 = $_POST["near_input_8"];
$be_add = $_POST["be_add"];
$re = $_POST["re"];
$le_add = $_POST["le_add"];
$glass_type = $_POST["glass_type"];
$glass_colour = $_POST["glass_colour"];
$glass_use = $_POST["glass_use"];
$pd = $_POST["pd"];

// second row
$visit1_no = $_POST["visit1_no"];
$dist1_input_1 = $_POST["dist1_input_1"];
$dist1_input_2 = $_POST["dist1_input_2"];
$dist1_input_3 = $_POST["dist1_input_3"];
$dist1_input_4 = $_POST["dist1_input_4"];
$dist1_input_5 = $_POST["dist1_input_5"];
$dist1_input_6 = $_POST["dist1_input_6"];
$dist1_input_7 = $_POST["dist1_input_7"];
$dist1_input_8 = $_POST["dist1_input_8"];
$near1_input_1 = $_POST["near1_input_1"];
$near1_input_2 = $_POST["near1_input_2"];
$near1_input_3 = $_POST["near1_input_3"];
$near1_input_4 = $_POST["near1_input_4"];
$near1_input_5 = $_POST["near1_input_5"];
$near1_input_6 = $_POST["near1_input_6"];
$near1_input_7 = $_POST["near1_input_7"];
$near1_input_8 = $_POST["near1_input_8"];
$be1_add = $_POST["be1_add"];
$re1 = $_POST["re1"];
$le1_add = $_POST["le1_add"];
$glass1_type = $_POST["glass1_type"];
$glass1_colour = $_POST["glass1_colour"];
$glass1_use = $_POST["glass1_use"];
$pd1 = $_POST["pd1"];
$dist2_input_1 = $_POST["dist2_input_1"];
$dist2_input_2 = $_POST["dist2_input_2"];
$dist2_input_3 = $_POST["dist2_input_3"];
$dist2_input_4 = $_POST["dist2_input_4"];
$dist2_input_5 = $_POST["dist2_input_5"];
$dist2_input_6 = $_POST["dist2_input_6"];
$dist2_input_7 = $_POST["dist2_input_7"];
$dist2_input_8 = $_POST["dist2_input_8"];
$near2_input_1 = $_POST["near2_input_1"];
$near2_input_2 = $_POST["near2_input_2"];
$near2_input_3 = $_POST["near2_input_3"];
$near2_input_4 = $_POST["near2_input_4"];
$near2_input_5 = $_POST["near2_input_5"];
$near2_input_6 = $_POST["near2_input_6"];
$near2_input_7 = $_POST["near2_input_7"];
$near2_input_8 = $_POST["near2_input_8"];
$be2_add = $_POST["be2_add"];
$re2 = $_POST["re2"];
$le2_add = $_POST["le2_add"];
$glass2_type = $_POST["glass2_type"];
$glass2_colour = $_POST["glass2_colour"];
$glass2_use = $_POST["glass2_use"];
$pd2 = $_POST["pd2"];


$dist3_input_1 = $_POST["dist3_input_1"];
$dist3_input_2 = $_POST["dist3_input_2"];
$dist3_input_3 = $_POST["dist3_input_3"];
$dist3_input_4 = $_POST["dist3_input_4"];
$dist3_input_5 = $_POST["dist3_input_5"];
$dist3_input_6 = $_POST["dist3_input_6"];
$dist3_input_7 = $_POST["dist3_input_7"];
$dist3_input_8 = $_POST["dist3_input_8"];
$near3_input_1 = $_POST["near3_input_1"];
$near3_input_2 = $_POST["near3_input_2"];
$near3_input_3 = $_POST["near3_input_3"];
$near3_input_4 = $_POST["near3_input_4"];
$near3_input_5 = $_POST["near3_input_5"];
$near3_input_6 = $_POST["near3_input_6"];
$near3_input_7 = $_POST["near3_input_7"];
$near3_input_8 = $_POST["near3_input_8"];
$be3_add = $_POST["be3_add"];
$re3 = $_POST["re3"];
$le3_add = $_POST["le3_add"];
$glass3_type = $_POST["glass3_type"];
$glass3_colour = $_POST["glass3_colour"];
$glass3_use = $_POST["glass3_use"];
$pd3 = $_POST["pd3"];
$dist4_input_1 = $_POST["dist4_input_1"];
$dist4_input_2 = $_POST["dist4_input_2"];
$dist4_input_3 = $_POST["dist4_input_3"];
$dist4_input_4 = $_POST["dist4_input_4"];
$dist4_input_5 = $_POST["dist4_input_5"];
$dist4_input_6 = $_POST["dist4_input_6"];
$dist4_input_7 = $_POST["dist4_input_7"];
$dist4_input_8 = $_POST["dist4_input_8"];
$near4_input_1 = $_POST["near4_input_1"];
$near4_input_2 = $_POST["near4_input_2"];
$near4_input_3 = $_POST["near4_input_3"];
$near4_input_4 = $_POST["near4_input_4"];
$near4_input_5 = $_POST["near4_input_5"];
$near4_input_6 = $_POST["near4_input_6"];
$near4_input_7 = $_POST["near4_input_7"];
$near4_input_8 = $_POST["near4_input_8"];
$be4_add = $_POST["be4_add"];
$re4 = $_POST["re4"];
$le4_add = $_POST["le4_add"];
$glass4_type = $_POST["glass4_type"];
$glass4_colour = $_POST["glass4_colour"];
$glass4_use = $_POST["glass4_use"];
$pd4 = $_POST["pd4"];
$advice = $_POST["advice"];
$fer = $_POST["fer"];

$query1 = "UPDATE `cc_glass_rx1` SET
  `dist1_input_1`='$dist1_input_1',
  `dist1_input_2`='$dist1_input_2',
  `dist1_input_3`='$dist1_input_3',
  `dist1_input_4`='$dist1_input_4',
  `dist1_input_5`='$dist1_input_5',
  `dist1_input_6`='$dist1_input_6',
  `dist1_input_7`='$dist1_input_7',
  `dist1_input_8`='$dist1_input_8',
  `near1_input_1`='$near1_input_1',
  `near1_input_2`='$near1_input_2',
  `near1_input_3`='$near1_input_3',
  `near1_input_4`='$near1_input_4',
  `near1_input_5`='$near1_input_5',
  `near1_input_6`='$near1_input_6',
  `near1_input_7`='$near1_input_7',
  `near1_input_8`='$near1_input_8',
  `be1_add`='$be1_add',
  `re1`='$re1',
  `le1_add`='$le1_add',
  `glass1_type`='$glass1_type',
  `glass1_colour`='$glass1_colour',
  `glass1_use`='$glass1_use',
  `pd1`='$pd1',
  `dist2_input_1`='$dist2_input_1',
  `dist2_input_2`='$dist2_input_2',
  `dist2_input_3`='$dist2_input_3',
  `dist2_input_4`='$dist2_input_4',
  `dist2_input_5`='$dist2_input_5',
  `dist2_input_6`='$dist2_input_6',
  `dist2_input_7`='$dist2_input_7',
  `dist2_input_8`='$dist2_input_8',
  `near2_input_1`='$near2_input_1',
  `near2_input_2`='$near2_input_2',
  `near2_input_3`='$near2_input_3',
  `near2_input_4`='$near2_input_4',
  `near2_input_5`='$near2_input_5',
  `near2_input_6`='$near2_input_6',
  `near2_input_7`='$near2_input_7',
  `near2_input_8`='$near2_input_8',
  `be2_add`='$be2_add',
  `re2`='$re2',
  `le2_add`='$le2_add',
  `glass2_type`='$glass2_type',
  `glass2_colour`='$glass2_colour',
  `glass2_use`='$glass2_use',
  `pd2`='$pd2',
  `dist3_input_1`='$dist3_input_1',
  `dist3_input_2`='$dist3_input_2',
  `dist3_input_3`='$dist3_input_3',
  `dist3_input_4`='$dist3_input_4',
  `dist3_input_5`='$dist3_input_5',
  `dist3_input_6`='$dist3_input_6',
  `dist3_input_7`='$dist3_input_7',
  `dist3_input_8`='$dist3_input_8',
  `near3_input_1`='$near3_input_1',
  `near3_input_2`='$near3_input_2',
  `near3_input_3`='$near3_input_3',
  `near3_input_4`='$near3_input_4',
  `near3_input_5`='$near3_input_5',
  `near3_input_6`='$near3_input_6',
  `near3_input_7`='$near3_input_7',
  `near3_input_8`='$near3_input_8',
  `be3_add`='$be3_add',
  `re3`='$re3',
  `le3_add`='$le3_add',
  `glass3_type`='$glass3_type',
  `glass3_colour`='$glass3_colour',
  `glass3_use`='$glass3_use',
  `pd3`='$pd3',
  `dist4_input_1`='$dist4_input_1',
  `dist4_input_2`='$dist4_input_2',
  `dist4_input_3`='$dist4_input_3',
  `dist4_input_4`='$dist4_input_4',
  `dist4_input_5`='$dist4_input_5',
  `dist4_input_6`='$dist4_input_6',
  `dist4_input_7`='$dist4_input_7',
  `dist4_input_8`='$dist4_input_8',
  `near4_input_1`='$near4_input_1',
  `near4_input_2`='$near4_input_2',
  `near4_input_3`='$near4_input_3',
  `near4_input_4`='$near4_input_4',
  `near4_input_5`='$near4_input_5',
  `near4_input_6`='$near4_input_6',
  `near4_input_7`='$near4_input_7',
  `near4_input_8`='$near4_input_8',
  `be4_add`='$be4_add',
  `re4`='$re4',
  `le4_add`='$le4_add',
  `glass4_type`='$glass4_type',
  `glass4_colour`='$glass4_colour',
  `glass4_use`='$glass4_use',
  `pd4`='$pd4'
WHERE id = $id";

 if ($conn->query($query1) === TRUE) {
    echo "Data updated successfully.";
} else {
    echo "Error updating data: " . $conn->error;
}


$sql = "UPDATE cc_glass_rx SET 
fees = '$fees',
visit_no='$visit_no',
dist_input_1 = '$dist_input_1',
dist_input_2 = '$dist_input_2',
dist_input_3 = '$dist_input_3',
dist_input_4 = '$dist_input_4',
dist_input_5 = '$dist_input_5',
dist_input_6 = '$dist_input_6',
dist_input_7 = '$dist_input_7',
dist_input_8 = '$dist_input_8',
near_input_1 = '$near_input_1',
near_input_2 = '$near_input_2',
near_input_3 = '$near_input_3',
near_input_4 = '$near_input_4',
near_input_5 = '$near_input_5',
near_input_6 = '$near_input_6',
near_input_7 = '$near_input_7',
near_input_8 = '$near_input_8',
be_add = '$be_add',
re = '$re',
le_add = '$le_add',
glass_type = '$glass_type',
glass_colour = '$glass_colour',
glass_use = '$glass_use',
pd = '$pd',
advice='$advice',
complaints='$complaints',
past_his='$past_his',
fer='$fer'
WHERE id = $id";
        if ($conn->query($sql) === TRUE) {
            echo "Data updated successfully.";
        } else {
            echo "Error updating data: " . $conn->error;
        }
        $conn->close();


?>